myFirstProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('courseMe/', include('courseMe.urls')),
    path('polls/', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new-question/', views.new_question, name='new_question'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django.forms import Form, CharField
from .models import Question, Choice


class QuestionForm(Form):
    question_text =  CharField(label="question text", max_length=200)
    first_choice = CharField(label="First choice", max_length=200)
    second_choice = CharField(label="Second choice", max_length=200)
    third_choice = CharField(label="Third choice", max_length=200)
    

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.urls import reverse
from django.views import generic

from .models import Choice, Question
from .forms import QuestionForm


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:100]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def new_question(request):
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
    
        if question_form.is_valid():
            q = Question(question_text=question_form.cleaned_data['question_text'], pub_date=timezone.now())
            q.save()
            q.choice_set.create(choice_text=question_form.cleaned_data['first_choice'], votes=0)
            q.choice_set.create(choice_text=question_form.cleaned_data['second_choice'], votes=0)
            q.choice_set.create(choice_text=question_form.cleaned_data['third_choice'], votes=0)
            
            return redirect(reverse('polls:index'))
    else:
        question_form = QuestionForm() 
        return render(request, 'polls/new-question.html', {'question_form': question_form,})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<br>
<input type="submit" value="Vote">
</form>

<a href="{% url 'polls:results' question.id %}">See results ?</a>
<a href="{% url 'polls:index' %}">Home</a>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/new-question.html
<html>

<body>
    <form action="{% url 'polls:new_question' %}" method="post">
        {% csrf_token %}
        {{ question_form|linebreaks }}
        {{ choice1_form|linebreaks }}
        {{ choice2_form|linebreaks }}
        {{ choice3_form|linebreaks }}
        <input type="submit" value="Add a new question">
    </form>
</body>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes}} vote{{ choice.votes|pluralize }}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:index' %}">Home</a>