courseMe/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from . import views

app_name = 'courseMe'

urlpatterns = [
    path('', login_required(views.HomeView.as_view()), name='home'),
    path('create_new_course', login_required(views.NewCourseView.as_view()), name='create_new_course'),
    path('delete_course/<pk>/', views.DeleteCourseView.as_view(), name='delete_course'),
    path('create_new_section/<int:course_id>/', views.NewSectionView.as_view(), name='create_new_section'),
    path('create_new_lesson/<int:course_id>/', views.NewLessonView.as_view(), name='create_new_lesson'),
    path('update_lesson/<pk>/', views.UpdateLessonView.as_view(), name='update_lesson'),
    path('update_section/<pk>/', views.UpdateSectionView.as_view(), name='update_section'),
    path('delete_lesson/<pk>/', views.DeleteLessonView.as_view(), name='delete_lesson'),
    path('course_detail/<int:pk>/', login_required(views.CourseDetailView.as_view()), name='course_detail')
    
] 

myFirstProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('courseMe/', include('courseMe.urls')),
    path('polls/', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new-question/', views.new_question, name='new_question'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

courseMe/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User


def lesson_directory_path(instance, filename):
    return 'courses_videos/{0}/{1}-{2}'.format(instance.course_owner, instance.name, filename)

class Course(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='my_own_courses', null=True)
    students = models.ManyToManyField(User, related_name='my_courses', blank=True)
    image = models.ImageField(default='courses_images/add_img.jpg', upload_to='courses_images')
    create_date = models.DateTimeField(auto_now=True)
    last_updated = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Section(models.Model):
    class Meta:
        ordering = ['section_number']

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='section', default=None)
    name = models.CharField(max_length=128)
    section_number = models.IntegerField(default=1)
    all_the_students_can_see = models.BooleanField(default=True)
    can_see = models.ManyToManyField(User, related_name='section_can_see', blank=True)

    def __str__(self):
        return self.name
    

class Lesson(models.Model):
    class Meta:
        ordering = ['lesson_number']

    section = models.ForeignKey(Section, on_delete=models.CASCADE, related_name='lesson', default=None)
    name = models.CharField(max_length=128)
    lesson_number = models.IntegerField(default=1)
    description = models.CharField(max_length=256, blank=True)
    lecturer = models.CharField(max_length=256)
    video = models.FileField(upload_to=lesson_directory_path,validators=[FileExtensionValidator(['mp4', 'avi', ])], null=True)  
    all_the_students_can_see = models.BooleanField(default=True)
    can_see = models.ManyToManyField(User, related_name='lesson_can_see', blank=True)
    
    def __str__(self):
        return self.name

courseMe/forms.py
from django import forms
from .models import Course, Section, Lesson


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ("name", "description", "image", "students", "is_public" )
        widgets = {
            'name' : forms.TextInput(attrs={"class": "prompt srch_explore", 'placeholder': 'Enter course name'}),
            'description' : forms.Textarea(attrs={'rows' : 3, 'placeholder' : 'Enter course description'}),
        }


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        exclude = ('course',)

    def __init__(self, *args, **kwargs):
        super(SectionForm, self).__init__(*args, **kwargs)
        for field in self.fields.values(): 
            if isinstance(field, (forms.CharField)):
                field.widget.attrs['class'] = 'form-control'


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = '__all__'
        widgets = {
            'video': forms.FileInput(attrs={'accept': 'video/*'}),
        }

    def __init__(self, course_id=None, *args, **kwargs):
        super(LessonForm, self).__init__(*args, **kwargs)
        for field in self.fields.values(): 
            if isinstance(field, (forms.CharField)):
                field.widget.attrs['class'] = 'form-control'
        if course_id:
            self.fields["section"] = forms.ModelChoiceField(Section.objects.filter(course=course_id))

courseMe/views.py
from django.views import generic
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User
from django.db.models import Q
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django import forms
from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import Course, Section, Lesson
from .forms import CourseForm, SectionForm, LessonForm


class HomeView(generic.ListView):
    model = Course
    template_name = "courseMe/dashboard.html"
    context_object_name = "courses"

    def get_queryset(self):
        return Course.objects.filter(Q(owner=self.request.user) | Q(is_public=True) | Q(students__id=self.request.user.id))


class CourseDetailView(PermissionRequiredMixin, generic.DetailView):
    model = Course
    template_name = 'courseMe/course_detail.html'
    context_object_name = "course"

    def has_permission(self):
        course = self.get_object()
        return (self.request.user == course.owner or course.is_public or self.request.user in course.students.all())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object()
        context["section_form"] = SectionForm(prefix="section")
        context["lesson_form"] = LessonForm(
            prefix="lesson", course_id=course.id)
        context["total_lessons"] = sum(
            len(section.lesson.all()) for section in course.section.all())
        return context


class NewCourseView(CreateView):
    template_name = "courseMe/‏‏create_new_course.html"
    form_class = CourseForm

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(NewCourseView, self).form_valid(form)


class NewLessonView(CreateView):
    form_class = LessonForm
    prefix = "lesson"

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def form_valid(self, form):
        course_id = self.kwargs["course_id"]
        course_owner = Course.objects.get(pk=course_id)
        form.instance.course_owner = course_owner
        return super(NewLessonView, self).form_valid(form)


class NewSectionView(CreateView):
    form_class = SectionForm
    prefix = "section"
    template_name = 'courseMe/dashboard.html'

    def get_success_url(self):
        return reverse('courseMe:course_detail', args=[self.kwargs["course_id"]])

    def form_valid(self, form):
        course_id = self.kwargs["course_id"]
        course = Course.objects.get(pk=course_id)
        form.instance.course = course
        return super(NewSectionView, self).form_valid(form)


class UpdateLessonView(UpdateView):
    model = Lesson
    form_class = LessonForm

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class UpdateSectionView(UpdateView):
    model = Section
    form_class = SectionForm

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')


class DeleteCourseView(DeleteView):
    model = Course
    success_url = reverse_lazy('courseMe:home')

    def delete(self, request, *args, **kwargs):
        if self.get_object().owner == request.user:
            return super(DeleteCourseView, self).delete(request, *args, **kwargs)


class DeleteLessonView(DeleteView):
    model = Lesson

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def delete(self, request, *args, **kwargs):
        if self.get_object().section.course.owner == request.user:
            return super(DeleteLessonView, self).delete(request, *args, **kwargs)

courseMe/templates/courseMe/course_detail.html
{% extends "courseMe/base.html" %}
{% load static %}

{% block content %}

<div class="_215b01">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<div class="section3125">
					<div class="row justify-content-center">
						<div class="col-xl-4 col-lg-5 col-md-6">
							<div class="preview_video">
								<div class="fcrse_img" data-toggle="modal">
									<img src="{{ course.image.url }}" alt="">
									{% if user == course.owner %}
									<div class="badge_seller">Your course</div>
									{% endif %}

								</div>
							</div>

						</div>
						<div class="col-xl-8 col-lg-7 col-md-6">
							<div class="_215b03">
								<h2>{{ course.name }}</h2>
								<span class="_215b04">{{ course.description }}</span>
							</div>

							<div class="_215b05">
								Last Updated: {{ course.last_updated|timesince }}
							</div>

							<div class="_215b05">
								Creator: {{ course.owner }}
							</div>

							{% if user == course.owner %}
							<ul class="_215b31">
								<li>
									<button type="button" class="btn_adcart" data-toggle="modal"
										data-target="#addSectionModal">Add Section</button>
								</li>

								<li>
									<button id="addLessonButton" type="button" class="btn_adcart" data-toggle="modal"
										data-target="#addLessonModal">Add lesson</button>
								</li>

								<li>
									<form method="post" action="{% url 'courseMe:delete_course' course.pk %}">
										{% csrf_token %}
										<button type="sumbit" class="btn_adcart">Remove course</button>
									</form>
								</li>
							</ul>
							{% endif %}
							<!-- Create lesson Modal -->
							<div class="modal fade" id="addLessonModal" tabindex="-1" role="dialog" aria-hidden="true">
								<div class="modal-dialog" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title">New lesson</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<form action="{% url 'courseMe:create_new_lesson' course_id=course.pk %}"
												method="post" enctype="multipart/form-data">
												{% csrf_token %}
												{{ lesson_form.as_p }}

												<div class="modal-footer">
													<button type="button" class="btn btn-secondary"
														data-dismiss="modal">Close</button>
													<button type="submit" class="btn btn-primary">Create lesson</button>
												</div>

											</form>
										</div>
									</div>
								</div>
							</div>


						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="_215b15 _byt1458">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">

				<div class="course_tabs">
					<nav>
						<div class="nav nav-tabs tab_crse justify-content-center" id="nav-tab" role="tablist">
							<a class="nav-item nav-link active" id="nav-courses-tab" data-toggle="tab"
								href="#nav-courses" role="tab" aria-selected="true">Courses Content</a>
						</div>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="_215b17">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<div class="course_tab_content">
					<div class="tab-content" id="nav-tabContent">

						<div class="tab-pane fade show active" id="nav-courses" role="tabpanel">
							<div class="crse_content">
								<h3>Course content</h3>
								<div class="_112456">
									<ul class="accordion-expand-holder">
										<li><span class="accordion-expand-all _d1452">Expand all</span></li>
										<li><span class="_fgr123"> {{ total_lessons }} Lessons</span></li>
										<li><span class="_fgr123">00:00:00</span></li>
									</ul>
								</div>
								<div id="accordion" class="ui-accordion ui-widget ui-helper-reset">
									{% for section in  course.section.all %}
									{% if section.all_the_students_can_see or user == course.owner or user in section.can_see.all %}

									<a href="javascript:void(0)"
										class="accordion-header ui-accordion-header ui-helper-reset ui-state-default ui-accordion-icons ui-corner-all">
										<div class="section-header-left">
											<span class="section-title-wrapper">
												<i class='uil uil-presentation-play crse_icon'></i>
												<span class="section-title-text">{{ section.section_number }}.
													{{ section.name }}</span>
											</span>
										</div>
										<div class="section-header-right">
											<span class="num-items-in-section">{{ section.lesson.all|length }}
												lessons</span>
											<span class="section-header-length">
												00:00
											</span>
										</div>
									</a>

									<div
										class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom">
										<div class="lecture-container">


											<table class="table ucp-table">
												<thead class="thead-s">
													<tr>
														<th class="text-center" scope="col">Lecture ID</th>
														<th class="cell-ta">Title</th>
														<th class="text-center" scope="col">Lecturer</th>
														<th class="text-center" scope="col">Description</th>
														<th class="text-center" scope="col">Preview</th>
														<th class="text-center" scope="col">Controls</th>
													</tr>
												</thead>
												<tbody>
													{% for lesson in section.lesson.all %}
													<tr>
														<td class="text-center">{{ lesson.lesson_number }}</td>
														<td class="cell-ta">{{ lesson.name }}</td>
														<td class="text-center">{{ lesson.lecturer }}</td>
														<td class="text-center">{{ leeson.description }}</td>
														<td class="text-center">
															{% if user == course.owner or lesson.all_the_students_can_see or user in lesson.can_see.all %}
															<button type="button" class="btn btn-primary"
																data-toggle="modal" data-target="#videoModal"
																value="{{ lesson.video.url }}">Preview</button>
															{% endif %}
														</td>

														<td class="text-center">
															{% if user == course.owner %}


															<form method="post" id="deleteLessonForm"
																action="{% url 'courseMe:delete_lesson' lesson.pk %}">
																{% csrf_token %}
																<a id="editLessonIcon" data-toggle="modal"
																	data-target="#editLessonModal" title="Edit"
																	class="gray-s" value={{ lesson.id }}>
																	<i class="uil uil-edit-alt"></i>
																</a>
																<a title="Remove" value={{ lesson.id }}>
																	<i class="uil uil-trash-alt"
																		onclick="document.getElementById('deleteLessonForm').submit();"></i>
																</a>
															</form>

															{% else %}
															<span class="badge badge-danger">You aren't course
																owner</span>
															{% endif %}


														</td>
													</tr>
										</div>
										{% endfor %}
										</tbody>
										</table>
										{% if user == course.owner %}
										<a href="#" data-toggle="modal" data-target="#editSectionModal">
											<i class="uil uil-edit-alt editSectionIcon" title="Edit section"
												value={{ section.id }}> </i>
										</a>
										{% endif %}
									</div>
								</div>
								{% endif %}

								{% endfor %}


							</div>

						</div>
					</div>

					{% if user == course.owner  %}
					<!-- Edit lesson Modal -->
					<div class="modal fade" id="editLessonModal" tabindex="-1" role="dialog" aria-hidden="true">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">Edit lesson</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<form id="editLessonForm" action="{% url 'courseMe:update_lesson' 0 %}"
										method="post">

									</form>
								</div>
							</div>
						</div>
					</div>

					<!-- Edit Section Modal -->
					<div class="modal fade" id="editSectionModal" tabindex="-1" role="dialog" aria-hidden="true">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">Edit Section</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<form id="editSectionForm" action="{% url 'courseMe:update_section' 0 %}"
										method="post">
									</form>
								</div>
							</div>
						</div>
					</div>

					<!-- Create section Modal -->
					<div class="modal fade" id="addSectionModal" tabindex="-1" role="dialog" aria-hidden="true">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">New Section</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<form action="{% url 'courseMe:create_new_section' course_id=course.pk %}"
										method="post">
										{% csrf_token %}
										{{ section_form.as_p }}

										<div class="modal-footer">
											<button type="button" class="btn btn-secondary"
												data-dismiss="modal">Close</button>
											<button type="submit" class="btn btn-primary">Create
												Section</button>
										</div>

									</form>
								</div>
							</div>
						</div>
					</div>
					{% endif %}

					<!-- Video Modal -->
					<div class="modal fade" id="videoModal" tabindex="-1" role="dialog"
						aria-labelledby="exampleModalLabel" aria-hidden="true">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title" id="exampleModalLabel">Lesson Preview</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<center>
										<video id='lesson-video-player' controls autoplay>
											<source src="" type="video/mp4">
											</source>
										</video>
									</center>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

{% endblock content %}

{% block scripts %}


<script>
	$("button[data-target='#videoModal']").click(function () {
		$('#lesson-video-player').attr('src', $(this).val());
	});
</script>

{% if user == course.owner %}
<script>
	$(document).ready(function () {
		$("button[data-target='#videoModal']").click(function () {
			$('#lesson-video-player').attr('src', $(this).val());
		});

		$('#id_lesson-can_see').select2({
			width: '100%'
		});

		$('#id_lesson-section').select2({
			width: '100%'
		});
		$('#id_section-can_see').select2({
			width: '100%'
		});

		$('label[for=id_lesson-can_see]').parent().hide();
		$('label[for=id_section-can_see]').parent().hide();

		$("#id_lesson-all_the_students_can_see").click(function () {
			if ($("#id_lesson-all_the_students_can_see").prop('checked')) {
				$('label[for=id_lesson-can_see]').parent().hide();
			} else {
				$('label[for=id_lesson-can_see]').parent().show();
			}
		});

		$("#id_section-all_the_students_can_see").click(function () {
			if ($("#id_section-all_the_students_can_see").prop('checked')) {
				$('label[for=id_section-can_see]').parent().hide();
			} else {
				$('label[for=id_section-can_see]').parent().show();
			}
		});







		$("#editLessonIcon").click(function () {
			$('#editLessonForm').attr('action', "/courseMe/update_lesson/" + $('#editLessonIcon').attr(
				'value') + '/');
			$.ajax({
				url: "/courseMe/update_lesson/" + $('#editLessonIcon').attr('value'),
				dataType: 'html',
				method: 'GET',
				success: function (data, status) {
					$('#editLessonForm').html(data);
					$('#editLessonForm').find('#id_can_see').select2({
						width: '100%'
					});
					$('#editLessonForm').find('#id_section').select2({
						width: '100%'
					});

				}
			});
		});

		$(".editSectionIcon").click(function () {
			$('#editSectionForm').attr('action', "/courseMe/update_section/" + $(this).attr('value') +
			'/');
			$.ajax({
				url: "/courseMe/update_section/" + $(this).attr('value'),
				dataType: 'html',
				method: 'GET',
				success: function (data, status) {
					$('#editSectionForm').html(data);
					$('#editSectionForm').find('#id_can_see').select2({
						width: '100%'
					});
					$('#editSectionForm').find('#id_section').select2({
						width: '100%'
					});

				}
			});
		});

	});
</script>
{% endif %}
{% endblock scripts %}

courseMe/templates/courseMe/dashboard.html
{% extends "courseMe/base.html" %}

{% block content %}
<h4 class="item_title">
    {% if courses %} Hello {{  user.get_username }} - You have {{ courses|length }} courses.
    {% else %}
    Hello {{  user.get_username }} - You don't have any courses.
    {% endif %}
</h4>

<div class="la5lo1">
    <div class="row">
        {% if courses %}
        {% for course in courses %}
        <div class="fcrse_1" style="width: 20%;">
            <a href="{% url 'courseMe:course_detail' pk=course.pk %}" class="fcrse_img">
                <img src="{{ course.image.url }}" alt="">
                {% if user == course.owner %}
									<div class="badge_seller">Your course</div>
                {% endif %}
                <div class="course-overlay">
                    <span class="play_btn1"><i class="uil uil-play"></i></span>

                </div>
            </a>
            <div class="fcrse_content">
                <div class="eps_dots more_dropdown">
                    <a href="#"><i class="uil uil-ellipsis-v"></i></a>
                    <div class="dropdown-content">
                        <span><i class="uil uil-exit"></i>Leave course</span>
                    </div>
                </div>
                <div class="vdtodt">
                    <span>Last update: {{ course.last_updated|timesince }}</span>
                </div>
                <a href="{% url 'courseMe:course_detail' pk=course.pk %}" class="crse14s">{{ course.name }}
                    <a class="crse-cate">{{ course.description }}</a>
                    <div class="auth1lnkprce">
                        <p class="cr1fot">By {{ course.owner }}</p>
                    </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}


    </div>
</div>

{% endblock content %}

courseMe/templates/courseMe/lesson_form.html
{% csrf_token %}
{{form.as_p}}

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Edit lesson</button>
</div>

courseMe/templates/courseMe/section_form.html
{% csrf_token %}
{{form.as_p}}

<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Edit Section</button>
</div>

courseMe/templates/courseMe/‏‏create_new_course.html
{% extends 'courseMe/base.html' %}
{% load static %}


{% block content %}
<h4 class="item_title">
	Create new course
</h4>

<div class="la5lo1">
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="basic_profile">
			<div class="basic_ptitle">
				<h3>Add information about the course</h4>
			</div>
			<div class="basic_form">
				<div class="row">
					<div class="col-lg-8">
						<div class="row">
							<div class="col-lg-6">
								<div class="ui search focus mt-30">
									<div class="ui left icon input swdh11 swdh19">
										{{ form.name }}
									</div>
								</div>
							</div>


							<div class="col-lg-12">
								<div class="ui search focus mt-30">
									<div class="ui form swdh30">
										<div class="field">
											{{ form.description }}
										</div>
									</div>
								</div>
							</div>

							<div class="col-lg-12">
								<div class="ui search focus mt-30">
									<div class="ui form swdh30">
										<label for="{{ form.is_public.auto_id }}">Public course ?</label>
										{{ form.is_public }}
									</div>
								</div>

										{{ form.students }}
							</div>

							<div class="col-lg-12" id="id_students">
								
							</div>

							<div class="col-lg-12">
								<div class="part_input mt-30 lbel25">
									<label>Choose course image</label>
									<div class="input-group">
										<div class="custom-file">
											{{ form.image }}
										</div>
									</div>
								</div>
							</div>
						</div>




						<button class="save_btn" type="submit">Create</button>
					</div>
				</div>
			</div>
		</div>
	</form>

</div>
{% endblock content %}

{% block scripts %}

<script>
	$(document).ready(function() {

		$('#id_students').select2({ width: '100%' , placeholder: 'Enter specific students to the course'});
		$('#id_students').next(".select2-container").hide();
		$("#id_is_public").click(function(){
			if($("#id_is_public").prop('checked'))
				$('#id_students').next(".select2-container").hide();			
			else
				$('#id_students').next(".select2-container").show();
			
		});
	});
</script>
{% endblock scripts %}